version: '2.3'

services:
  worker:
    image: myoung34/github-runner:latest
    environment:
      ORG_NAME: ${GITHUB_ACTIONS_ORG_NAME:-rnanosaur}
      RUNNER_NAME: ${GITHUB_ACTIONS_RUNNER_NAME}
      ACCESS_TOKEN: ${GITHUB_ACTIONS_ACCESS_TOKEN}
      RUNNER_WORKDIR: ${PWD}/github-actions
      RUNNER_SCOPE: 'org'
      LABELS: linux,gpu
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '${PWD}/github-actions:${PWD}/github-actions'
      # note: a quirk of docker-in-docker is that this path
      # needs to be the same path on host and inside the container,
      # docker mgmt cmds run outside of docker but expect the paths from within