version: '2.3'

services:
  worker:
    image: myoung34/github-runner:latest
    restart: always
    environment:
      ORG_NAME: ${GITHUB_ACTIONS_ORG_NAME:-rnanosaur}
      RUNNER_NAME: ${GITHUB_ACTIONS_RUNNER_NAME}
      ACCESS_TOKEN: ${GITHUB_ACTIONS_ACCESS_TOKEN}
      RUNNER_WORKDIR: ${PWD}/github-actions
      RUNNER_SCOPE: 'org'
      LABELS: linux,gpu,Jetson
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '${PWD}/github-actions:${PWD}/github-actions'
      # note: a quirk of docker-in-docker is that this path
      # needs to be the same path on host and inside the container,
      # docker mgmt cmds run outside of docker but expect the paths from within
      - '/var/lib/dpkg/status:/var/lib/dpkg/status'
  # Watchtower - Check if new images are available
  watchtower: # https://containrrr.dev/watchtower
    image: containrrr/watchtower
    restart: always
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/.docker/config.json:/config.json
    command: --interval 43200 # Check every half day
  portainerservice:
    image: portainer/portainer
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9000:9000"

volumes:
  portainer_data: